/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stream;

public class App {

  public static StreamTest streamTest = new StreamTest();

  public static void main(String[] args) {
    run();
  }
  
  public static void run() {
    streamTest.run();
  }

}
